### ISSUE TITLE
Jenkins Issue

### ISSUE THREAD

**Issue by kulsv** [airavata-courses/Rangers#50]
Hi Team,

Changes in UI branch and notification_blue branch triggers the Jenkins job fine.
But, when I pushed any change to room_blue and room_green, Building of notification_blue is being triggered. And this notification_blue is taking too long and displays: "‘notificationservice’ is offline" as error.
Here are some of the builds triggered by rom_blue/room_green commits:

http://149.165.157.130:8080/job/notification-blue/5/
http://149.165.157.130:8080/job/notification-blue/6/
http://149.165.157.130:8080/job/notification-blue/7/
http://149.165.157.130:8080/job/notification-blue/8/

Please let me know if my understanding of triggering jobs is wrong.

Thanks,
Shweta

**Comment by rohankasture** [comment]
Hi Shweta,

The room service does not have blue-green deployment as it accesses a single database and it is kind of tricky to implement the same for such microservices. We forgot to delete the room-blue and room-green branches. We were unable to ssh into the VM where notification service resides due to some Jetstream issue. We have created another instance and deployed this service. You can test now.
Please let me know if you have any questions.

Thanks,
Rohan

**Comment by kulsv** [comment]
This is working fine now. Rest all looks good to me. Blue-Green deployment works fine too. Closing this issue.
